### ISSUE TITLE
Imports issue

### ISSUE THREAD

**Issue by mitola** [KrOverdulve/android-post-webview#1]
When trying to test and reintegrate your solution into my project i came across the issue in InterceptingWebViewClient.java with following imports:

import com.squareup.mimecraft.FormEncoding;
import com.squareup.okhttp.OkHttpClient;

Is it possible that you provide these 2 classes to the project aswell ?

**Comment by KrOverdulve** [comment]
Hi,

The dependency resolution for these two libraries is done by gradle in the
build.gradle file:

dependencies {

```
compile 'com.android.support:appcompat-v7:+'
```

!    compile 'com.squareup.okhttp:okhttp:1.3.0'

!    compile 'com.squareup.mimecraft:mimecraft:1.1.0'

```
compile 'org.jsoup:jsoup:1.7.2'
```

}

When importing the code in your own project, you can download the jars
manually, use maven, or gradle. See this link to find libraries:
http://gradleplease.appspot.com/

Good luck.

Cheers,
Kristof.

On Tue, Jun 3, 2014 at 11:13 AM, Matjaz notifications@github.com wrote:

> When trying to test and reintegrate your solution into my project i came
> across the issue in InterceptingWebViewClient.java with following imports:
> 
> import com.squareup.mimecraft.FormEncoding;
> import com.squareup.okhttp.OkHttpClient;
> 
> Is it possible that you provide these 2 classes to the project aswell ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeejOow/android-post-webview/issues/1.

## 

Met vriendelijke groeten,
Kristof Overdulve.
