### ISSUE TITLE
some post issues

### ISSUE THREAD

**Issue by mysteryzzp** [KrOverdulve/android-post-webview#3]
when the script is like this:
`HTMLFormElement.prototype._submit = HTMLFormElement.prototype.submit;
HTMLFormElement.prototype.submit = interceptor;
    window.addEventListener('submit', function(e) {
        interceptor(e);
    }, false);
    function interceptor(e) {
        var frm = e ? e.target : this;
        frm._submit();
    }`

in some websites, it is ok. 
but in the other websites,it error.
i must delete the `window.addEventListener` sentence.

could you help me.

**Comment by KrOverdulve** [comment]
Hi,

Hmm .. it might indeed be that some websites would throw errors as it's a very experimental piece of code. Could you show me the exact error?

With kind regards,
Kristof.

**Comment by mysteryzzp** [comment]
@KeejOow 

I do not know what the exact error is.
it is a login page,when i click the submit button, many requests invoke.
i found the requests are ok,it successfully login.
but it seems a more unnecessary request invoked.
so the page jump to an error page.

login in here: https://www.baidu.com/
but when i delete  window.addEventListener sentence, it goes ok.

**Comment by mysteryzzp** [comment]
I'm sorry. 
it is goes ok.
maybe it's the website's fault, and they fix it?
